### ISSUE TITLE
errors after `react-native link` command

### ISSUE THREAD

**Issue by AliMeer** [thecryptobee/BitHyve-Wallet#2]
Following issue occurs after `react-native link` is executed

```
rnpm-install info Linking assets to ios project 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'pbxprojPath' of null

TypeError: Cannot read property 'pbxprojPath' of null
    at Object.linkAssetsIOS [as copyAssets] (/Users/susmit/Desktop/MyMoneyApp/node_modules/react-native/local-cli/link/ios/copyAssets.js:24:47)
    at Object.keys.forEach.platform (/Users/susmit/Desktop/MyMoneyApp/node_modules/react-native/local-cli/link/link.js:104:16)
    at Array.forEach (<anonymous>)
    at linkAssets (/Users/susmit/Desktop/MyMoneyApp/node_modules/react-native/local-cli/link/link.js:94:32)
    at tasks.push (/Users/susmit/Desktop/MyMoneyApp/node_modules/react-native/local-cli/link/link.js:171:20)
```

**Comment by AliMeer** [comment]
`sudo react-native upgrade` will resolve the issue
